services:

  # MongoDB services
  mongodb:
    container_name: db-container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongodb:/data/db

  # Node API service
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      DB_URI: 'mongodb://mongodb:27017'
      SECRET_REFRESH_TOKEN: c0lKV2kza043bGl5N0FIMmlqeWddfOXVDcsdfdTphd1dRCZDMyOHgfmJrOG1WYlcdfd0UnBFVjhh
      REFRESH_TOKEN_EXPIRY: '7d'
      SECRET_ACCESS_TOKEN: ApZq1LbEnLgEZoE3_R-MuJgNFksop0h04rzMQO3TOJgjk45_iu-tiHeBmZltAcrv
      ACCESS_TOKEN_EXPIRY: '15m'
    depends_on:
      - mongodb

volumes:
  mongodb: {}
